name: Hugo Build and Deploy

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout repository  # 检出仓库
      uses: actions/checkout@v2

    - name: Setup Hugo  # 设置 Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build and Deploy  # 构建和部署
      run: |
        hugo --minify
        # 添加部署步骤，例如将生成的静态文件部署到 GitHub Pages 或其他托管服务上
